### ISSUE TITLE
Добавить якутские буквы

### ISSUE THREAD

**Issue by tegorov** [sakhatyla/SakhaTyla.Mobile#3]
Добавить как на сайте якутские буквы

![Снимок экрана 2021-08-30 в 12 25 13](https://user-images.githubusercontent.com/42921436/131280751-d9b22c11-96c9-420f-9433-62774b493f27.png)

**Comment by bacr** [comment]
В целях распространения использования якутских клавиатур, предлагаю не делать такую фичу в приложении.
